config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers

  root 'main#index'
end

app/models/lesson.rb
class Lesson
  def self.lessons
    (1..100).to_a
  end
  def self.parts
    (1..3).to_a
  end
  def self.lessons_with_parts
    self.lessons.product(parts)
  end
  def self.next?(current_lesson_and_part, test_lesson_and_part)
    current_index = Lesson.lessons_with_parts.index(current_lesson_and_part)
    test_index = Lesson.lessons_with_parts.index(test_lesson_and_part)
    current_index != nil && test_index != nil && test_index == current_index + 1
  end
end

app/models/student_class.rb
class StudentClass < ActiveRecord::Base
  belongs_to :teacher, class_name: 'User', foreign_key: 'teacher_user_id'
  has_many :student_users, class_name: 'User', foreign_key: 'student_class_id'

  def students
    self.student_users.map{ |u| u.extend(Student) }
  end
end

app/models/student_record.rb
class StudentRecord < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :student_record, dependent: :delete
  has_many :student_classes, foreign_key: 'teacher_user_id' # for when this is a teacher
  belongs_to :student_class, foreign_key: 'student_class_id' # for when this is a student
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end

  def new
    @student = User.new().extend Student
  end

  def create
    user = User.new(params[:student].permit(:first_name, :last_name))
    @student = RegisterStudentContext.call(user)

    redirect_to student_url(@student)
  end

  def update
    user = User.find_by_id(params[:id])
    if(user)
      progress = OpenStruct.new(lesson: params[:student][:progress_lesson], part: params[:student][:progress_part])
      @student, status = UpdateStudentProgressContext.call(user, progress)
      flash[:notice] = "You can only proceed to the next part." unless status == :success
      redirect_to student_url(@student)
    else
      render template: "students/unknown"
    end
  end

  def show
    set_student_or_render_unknown
  end

  def edit
    set_student_or_render_unknown
  end

  private

  def set_student_or_render_unknown
    user = User.where(id: params[:id], is_teacher: false).first
    if(user)
      @student = user.extend Student
    else
      respond_to do |format|
        format.html { render template: "students/unknown", status: 404 }
        format.json { render json: { error: "Unknown Student" }.to_json, status: 404}
      end
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
  end
  def show
    user = User.where(id: params[:id], is_teacher: true).first
    if(user)
      @teacher = user.extend Teacher
    else
      respond_to do |format|
        format.html { render template: "teachers/unknown", status: 404 }
        format.json { render json: { error: "Unknown Teacher" }.to_json, status: 404}
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  def lessons
    (1..100).map{|n| ["L#{n}",n]}
  end
  def parts
    (1..3).map{|n| ["P#{n}",n]}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edux</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h2>
  Welcome to EduX
</h2>
<h3>
  — the student education application of Company X.
</h3>
<h4>Available Portals:</h4>
<ul>
  <li><%= link_to "Teachers", teachers_path %></li>
  <li><%= link_to "Students", students_path %></li>
</ul>

app/views/students/edit.html.erb
<h2>Student Progress Update</h2>

<p>
  Please indicate the progress the student has made:
</p>

<%= form_for @student, {url: {action: "update"}, method: :put} do |f| %>
  <%= @student.full_name %>

  <%= f.label :progress %>
  <%= f.select :progress_lesson, lessons, {}, {:id => 'progress_lesson'} %>
  <%= f.select :progress_part, parts, {}, {:id => 'progress_part'} %>

  <%= f.submit "Update" %>
<% end %>

app/views/students/index.html.erb
<h2>EduX — Students</h2>
<p>
  This is the Student portal for EduX. Here you may <%= link_to "Register", new_student_path %> or go <%= link_to "Back", root_path %>.
</p>

app/views/students/new.html.erb
<h2>New Student Registration</h2>

<p>
  Please fill in the following form to register:
</p>

<%= form_for @student, url: {action: "create"} do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, :id => 'first_name' %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name, :id => 'last_name' %>
  <%= f.submit "Register" %>
<% end %>

app/views/students/show.html.erb
<h2>EduX — Student Progress</h2>

<p>
  This page shows the student progress for <%= @student.full_name %>:
  <%= @student.progress %>. You may <%= link_to "Return", students_url %> to the students portal.
</p>

app/views/students/unknown.html.erb
<h2>Unknown Student</h2>

<p>
  There is no such student. <%= link_to "Return", students_url %>
</p>

app/views/teachers/index.html.erb
<h2>EduX — Teachers</h2>
<p>
  This is the Teacher portal for EduX. Here you may go <%= link_to "Back", root_path %>.
</p>

app/views/teachers/show.html.erb
<h2>Teacher Page</h2>

<p>
  This page shows the information for the teacher <%= @teacher.full_name %>.
  You may <%= link_to "Return", teachers_url %> to the teachers portal. Here are the classes:
</p>
<ul>
  <% for student_class in @teacher.student_classes %>
    <li>
      <%= student_class.name %>
      <ul>
        <% for student in student_class.students %>
          <li><%= student.full_name %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/teachers/unknown.html.erb
<h2>Unknown Teacher</h2>

<p>
  There is no such teacher. <%= link_to "Return", teachers_url %>
</p>